# Nous allons travailler sur la meteo.

### D'abord nous allons verifié nos URL

#### Ici nous allons mettre nos import:

In [9]:
import pandas as pd

Url des données energies:

In [10]:
url_energy = "https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv"
df_energy = pd.read_csv(url_energy)

Chargement des données CO2/climats

In [11]:
url_co2 = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"
df_co2 = pd.read_csv(url_co2)

In [12]:
print(f"Taille Energy: {df_energy.shape}")
print(f"Taille CO2: {df_co2.shape}")

Taille Energy: (23232, 130)
Taille CO2: (50411, 79)

### Explorons nos données Brut.

In [51]:
list(df_energy.columns)

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'biofuel_cons_change_pct',
 'biofuel_cons_change_twh',
 'biofuel_cons_per_capita',
 'biofuel_consumption',
 'biofuel_elec_per_capita',
 'biofuel_electricity',
 'biofuel_share_elec',
 'biofuel_share_energy',
 'carbon_intensity_elec',
 'coal_cons_change_pct',
 'coal_cons_change_twh',
 'coal_cons_per_capita',
 'coal_consumption',
 'coal_elec_per_capita',
 'coal_electricity',
 'coal_prod_change_pct',
 'coal_prod_change_twh',
 'coal_prod_per_capita',
 'coal_production',
 'coal_share_elec',
 'coal_share_energy',
 'electricity_demand',
 'electricity_demand_per_capita',
 'electricity_generation',
 'electricity_share_energy',
 'energy_cons_change_pct',
 'energy_cons_change_twh',
 'energy_per_capita',
 'energy_per_gdp',
 'fossil_cons_change_pct',
 'fossil_cons_change_twh',
 'fossil_elec_per_capita',
 'fossil_electricity',
 'fossil_energy_per_capita',
 'fossil_fuel_consumption',
 'fossil_share_elec',
 'fossil_share_energy',
 'gas_cons_change_pct',
 'gas_cons_change_twh',
 'gas_consumption',
 'gas_elec_per_capita',
 'gas_electricity',
 'gas_energy_per_capita',
 'gas_prod_change_pct',
 'gas_prod_change_twh',
 'gas_prod_per_capita',
 'gas_production',
 'gas_share_elec',
 'gas_share_energy',
 'greenhouse_gas_emissions',
 'hydro_cons_change_pct',
 'hydro_cons_change_twh',
 'hydro_consumption',
 'hydro_elec_per_capita',
 'hydro_electricity',
 'hydro_energy_per_capita',
 'hydro_share_elec',
 'hydro_share_energy',
 'low_carbon_cons_change_pct',
 'low_carbon_cons_change_twh',
 'low_carbon_consumption',
 'low_carbon_elec_per_capita',
 'low_carbon_electricity',
 'low_carbon_energy_per_capita',
 'low_carbon_share_elec',
 'low_carbon_share_energy',
 'net_elec_imports',
 'net_elec_imports_share_demand',
 'nuclear_cons_change_pct',
 'nuclear_cons_change_twh',
 'nuclear_consumption',
 'nuclear_elec_per_capita',
 'nuclear_electricity',
 'nuclear_energy_per_capita',
 'nuclear_share_elec',
 'nuclear_share_energy',
 'oil_cons_change_pct',
 'oil_cons_change_twh',
 'oil_consumption',
 'oil_elec_per_capita',
 'oil_electricity',
 'oil_energy_per_capita',
 'oil_prod_change_pct',
 'oil_prod_change_twh',
 'oil_prod_per_capita',
 'oil_production',
 'oil_share_elec',
 'oil_share_energy',
 'other_renewable_consumption',
 'other_renewable_electricity',
 'other_renewable_exc_biofuel_electricity',
 'other_renewables_cons_change_pct',
 'other_renewables_cons_change_twh',
 'other_renewables_elec_per_capita',
 'other_renewables_elec_per_capita_exc_biofuel',
 'other_renewables_energy_per_capita',
 'other_renewables_share_elec',
 'other_renewables_share_elec_exc_biofuel',
 'other_renewables_share_energy',
 'per_capita_electricity',
 'primary_energy_consumption',
 'renewables_cons_change_pct',
 'renewables_cons_change_twh',
 'renewables_consumption',
 'renewables_elec_per_capita',
 'renewables_electricity',
 'renewables_energy_per_capita',
 'renewables_share_elec',
 'renewables_share_energy',
 'solar_cons_change_pct',
 'solar_cons_change_twh',
 'solar_consumption',
 'solar_elec_per_capita',
 'solar_electricity',
 'solar_energy_per_capita',
 'solar_share_elec',
 'solar_share_energy',
 'wind_cons_change_pct',
 'wind_cons_change_twh',
 'wind_consumption',
 'wind_elec_per_capita',
 'wind_electricity',
 'wind_energy_per_capita',
 'wind_share_elec',
 'wind_share_energy']

In [52]:
df_energy.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

On choisit les colonnes importantes du data frame Energy et on crée un nouveau dataframe a partir de celui_ci :

In [53]:
df_energy_columns = ["country","year","iso_code","population","gdp","fossil_share_energy","coal_share_energy","renewables_share_energy", "low_carbon_share_energy","energy_per_capita","energy_per_gdp"]

In [54]:
df_energy_clean =  df_energy[df_energy_columns].copy()

On garde nos données seulement à partir des années 90.

In [55]:
df_energy_clean = df_energy_clean[df_energy_clean["year"]>=1990]

In [56]:
df_energy_clean.head()

,country,year,iso_code,population,gdp,fossil_share_energy,coal_share_energy,renewables_share_energy,low_carbon_share_energy,energy_per_capita,energy_per_gdp
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
df_energy_clean.isnull().sum()

country                       0
year                          0
iso_code                   2845
population                 2424
gdp                        4983
fossil_share_energy        6525
coal_share_energy          6525
renewables_share_energy    6525
low_carbon_share_energy    6525
energy_per_capita          2598
energy_per_gdp             5000
dtype: int64

On vire les régions avec un ISO null. Un ISO Null veut dire que c'est une région du monde et cela ne nous interesse pas.

In [58]:
df_energy_clean= df_energy_clean.dropna(subset=["iso_code"])

In [59]:
print(df_energy_clean.shape)
print(df_energy_clean.isnull().sum())

(7565, 11)
country                       0
year                          0
iso_code                      0
population                   48
gdp                        2156
fossil_share_energy        4800
coal_share_energy          4800
renewables_share_energy    4800
low_carbon_share_energy    4800
energy_per_capita           211
energy_per_gdp             2173
dtype: int64

On a encore trop de Nan pour faire un processus de Machine Learning fiable. on va suprimmé les lignes Nan de fossil_share_energy et "renewable_share_energy

In [60]:
df_energy_clean = df_energy_clean.dropna(subset=["fossil_share_energy","renewables_share_energy"])

# On vérifie la taille restante

print (f"Nouvelle taille : {df_energy_clean.shape}")

Nouvelle taille : (2765, 11)

In [61]:
print(df_energy_clean.isnull().sum())

country                      0
year                         0
iso_code                     0
population                   0
gdp                        160
fossil_share_energy          0
coal_share_energy            0
renewables_share_energy      0
low_carbon_share_energy      0
energy_per_capita            0
energy_per_gdp             160
dtype: int64

Il reste des Nan. on va aussi les suprimmé comme cela notre Dataframe est totalement propre.

In [62]:
df_energy_clean = df_energy_clean.dropna(subset=["gdp"])
print(f"taille finale : {df_energy_clean.shape}")

taille finale : (2605, 11)

Nous avons un Dataframe Dense pour df_clean_energy. Nous passons au nettoyage du dataset df_co2.

In [64]:
list(df_co2.columns)

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'cement_co2',
 'cement_co2_per_capita',
 'co2',
 'co2_growth_abs',
 'co2_growth_prct',
 'co2_including_luc',
 'co2_including_luc_growth_abs',
 'co2_including_luc_growth_prct',
 'co2_including_luc_per_capita',
 'co2_including_luc_per_gdp',
 'co2_including_luc_per_unit_energy',
 'co2_per_capita',
 'co2_per_gdp',
 'co2_per_unit_energy',
 'coal_co2',
 'coal_co2_per_capita',
 'consumption_co2',
 'consumption_co2_per_capita',
 'consumption_co2_per_gdp',
 'cumulative_cement_co2',
 'cumulative_co2',
 'cumulative_co2_including_luc',
 'cumulative_coal_co2',
 'cumulative_flaring_co2',
 'cumulative_gas_co2',
 'cumulative_luc_co2',
 'cumulative_oil_co2',
 'cumulative_other_co2',
 'energy_per_capita',
 'energy_per_gdp',
 'flaring_co2',
 'flaring_co2_per_capita',
 'gas_co2',
 'gas_co2_per_capita',
 'ghg_excluding_lucf_per_capita',
 'ghg_per_capita',
 'land_use_change_co2',
 'land_use_change_co2_per_capita',
 'methane',
 'methane_per_capita',
 'nitrous_oxide',
 'nitrous_oxide_per_capita',
 'oil_co2',
 'oil_co2_per_capita',
 'other_co2_per_capita',
 'other_industry_co2',
 'primary_energy_consumption',
 'share_global_cement_co2',
 'share_global_co2',
 'share_global_co2_including_luc',
 'share_global_coal_co2',
 'share_global_cumulative_cement_co2',
 'share_global_cumulative_co2',
 'share_global_cumulative_co2_including_luc',
 'share_global_cumulative_coal_co2',
 'share_global_cumulative_flaring_co2',
 'share_global_cumulative_gas_co2',
 'share_global_cumulative_luc_co2',
 'share_global_cumulative_oil_co2',
 'share_global_cumulative_other_co2',
 'share_global_flaring_co2',
 'share_global_gas_co2',
 'share_global_luc_co2',
 'share_global_oil_co2',
 'share_global_other_co2',
 'share_of_temperature_change_from_ghg',
 'temperature_change_from_ch4',
 'temperature_change_from_co2',
 'temperature_change_from_ghg',
 'temperature_change_from_n2o',
 'total_ghg',
 'total_ghg_excluding_lucf',
 'trade_co2',
 'trade_co2_share']

On choisit les colonens qui nous interessent le plus :

In [65]:
cols_co2 = [
    'country', 'year', 'iso_code', 'co2', 'co2_per_capita', 
    'coal_co2', 'gas_co2', 'oil_co2', 'share_global_co2', 
    'temperature_change_from_co2'
]

df_co2_clean = df_co2[cols_co2].copy()

On va faire notre Merge sur le Iso_code et l'année pour evité les erreurs de frappe dans le nom des pays.

In [66]:
# On nettoie les nan sur la colonne iso_code
df_co2_clean = df_co2_clean.dropna(subset=['iso_code'])

# On nettoie les lignes sans données CO2 car c'est le fond de notre sujet
df_co2_clean = df_co2_clean.dropna(subset=["co2","co2_per_capita"])

# On supprimme aussi les années en dessous de 1990 comme on l'a fait sur df_energy_clean
df_co2_clean = df_co2_clean[df_co2_clean["year"]>=1990]

print(f" Taille de notre dataset CO2 : {df_co2_clean.shape}")

 Taille de notre dataset CO2 : (7442, 10)

In [68]:
df_co2_clean.isnull().sum()

country                           0
year                              0
iso_code                          0
co2                               0
co2_per_capita                    0
coal_co2                       2690
gas_co2                        3185
oil_co2                           8
share_global_co2                  0
temperature_change_from_co2       0
dtype: int64

# On regarde les pays qui ont Nan pour gas et coal et voire si cela s'explique ou si c'est un manque de donnée.

In [ ]:
pays_manquants = df_co2_clean[df_co2_clean["coal_co2"].isna()]["country"].unique()
print(f"Nombre de pays avec données manquantes : {len(pays_manquants)}")
print(pays_manquants)

Nous pouvons voire que la majorité des pays listé entre dans deux catégories. Des pays porté principalement sur le petrole pour son energie ou des pays comme le Tchad ou l'Angola le suivis statistique peut être complexe faute de moyen. Je decide donc pour gardé l'impact de ces pays dans mon ML de mettre ces données manquantes à 0.

In [70]:
df_co2_clean[["coal_co2","gas_co2","oil_co2"]] = df_co2_clean[["coal_co2","gas_co2","oil_co2"]].fillna(0)

On lance le merge :

In [73]:
df_final = pd.merge(
    df_energy_clean,
    df_co2_clean,
    on=["iso_code","year"],
    how="inner"
)

On suprimme une des colonnes country car elles est apparue en double

In [ ]:
df_final["country"] = df_final["country_x"]
df_final = df_final.drop(columns=["country_x","country_y"])

In [78]:
# 5. Le verdict
print(f"\nShape final du dataset : {df_final.shape}")
df_final.head()

Shape final du dataset : (2605, 18)

,year,iso_code,population,gdp,fossil_share_energy,coal_share_energy,renewables_share_energy,low_carbon_share_energy,energy_per_capita,energy_per_gdp,co2,co2_per_capita,coal_co2,gas_co2,oil_co2,share_global_co2,temperature_change_from_co2,country
0,1990,DZA,25375815.0,1.178432e+11,99.881,2.433,0.119,0.119,12412.359,2.673,75.892,2.991,2.942,38.908,23.204,0.334,0.001,Algeria
1,1991,DZA,25987937.0,1.211051e+11,99.739,2.534,0.261,0.261,12009.229,2.577,77.976,3.000,2.689,38.428,26.066,0.336,0.001,Algeria
2,1992,DZA,26628570.0,1.279827e+11,99.827,2.935,0.173,0.173,12025.688,2.502,79.284,2.977,2.378,31.932,28.678,0.352,0.001,Algeria
3,1993,DZA,27277042.0,1.302758e+11,99.671,2.569,0.329,0.329,10924.754,2.287,81.306,2.981,1.924,36.098,27.993,0.357,0.001,Algeria
4,1994,DZA,27887277.0,1.342799e+11,99.847,2.388,0.153,0.153,10826.482,2.248,87.848,3.150,2.286,37.386,30.450,0.382,0.001,Algeria

In [79]:
cols = list(df_final.columns)
cols.remove("country")
cols.insert(0, "country")
df_final = df_final[cols]

df_final.head()

,country,year,iso_code,population,gdp,fossil_share_energy,coal_share_energy,renewables_share_energy,low_carbon_share_energy,energy_per_capita,energy_per_gdp,co2,co2_per_capita,coal_co2,gas_co2,oil_co2,share_global_co2,temperature_change_from_co2
0,Algeria,1990,DZA,25375815.0,1.178432e+11,99.881,2.433,0.119,0.119,12412.359,2.673,75.892,2.991,2.942,38.908,23.204,0.334,0.001
1,Algeria,1991,DZA,25987937.0,1.211051e+11,99.739,2.534,0.261,0.261,12009.229,2.577,77.976,3.000,2.689,38.428,26.066,0.336,0.001
2,Algeria,1992,DZA,26628570.0,1.279827e+11,99.827,2.935,0.173,0.173,12025.688,2.502,79.284,2.977,2.378,31.932,28.678,0.352,0.001
3,Algeria,1993,DZA,27277042.0,1.302758e+11,99.671,2.569,0.329,0.329,10924.754,2.287,81.306,2.981,1.924,36.098,27.993,0.357,0.001
4,Algeria,1994,DZA,27887277.0,1.342799e+11,99.847,2.388,0.153,0.153,10826.482,2.248,87.848,3.150,2.286,37.386,30.450,0.382,0.001

In [80]:
# Sauvegarde du dataset propre pour la suite du projet
df_final.to_csv('energy_climat_clean.csv', index=False)
print("Fichier sauvegardé avec succès !")

Fichier sauvegardé avec succès !